# Generated by Django 4.2.27 on 2026-01-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='format',
            field=models.CharField(blank=True, choices=[('paperback', 'Paperback'), ('hardcover', 'Hardcover'), ('mass_market', 'Mass Market Paperback')], max_length=32),
        ),
    ]
