# Generated by Django 4.2.27 on 2026-01-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='created_from',
            field=models.CharField(blank=True, help_text='csv, manual, api, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='seller_sku',
            field=models.CharField(blank=True, help_text='Seller’s internal reference / SKU', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('sold', 'Sold'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status'], name='listings_li_status_63af6d_idx'),
        ),
    ]
