# Generated by Django 4.2.27 on 2025-12-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn10', models.CharField(blank=True, db_index=True, help_text='Primary identifier when available', max_length=10, null=True, unique=True)),
                ('isbn13', models.CharField(blank=True, db_index=True, max_length=13, null=True)),
                ('title', models.CharField(max_length=512)),
                ('author', models.CharField(blank=True, max_length=512)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=32)),
                ('format', models.CharField(blank=True, help_text='Hardcover, Paperback, etc.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='catalog_boo_title_3a1ffe_idx'), models.Index(fields=['author'], name='catalog_boo_author_66025a_idx')],
            },
        ),
    ]
