# Generated by Django 4.2.27 on 2025-12-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image of the book', null=True, upload_to='covers/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_openlibrary_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
