# Generated by Django 4.2.27 on 2025-12-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_cover_image_book_cover_openlibrary_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image of the book', null=True, upload_to='catalog/covers/'),
        ),
    ]
