# Generated by Django 4.2.27 on 2025-12-21 12:38

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image of the book', null=True, upload_to=catalog.models.get_catalog_upload_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_openlibrary_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn13',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True),
        ),
    ]
