# Generated by Django 4.2.27 on 2025-12-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_book_already_read_count_book_amazon_asin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating_avg',
            field=models.FloatField(default=2.0),
        ),
    ]
