# Generated by Django 4.2.27 on 2026-01-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_book_rating_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating_avg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
