# Generated by Django 4.2.27 on 2026-01-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_book_rating_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_enriched',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn10',
            field=models.CharField(blank=True, db_index=True, help_text='Primary enrichment identifier when available (by design)', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn13',
            field=models.CharField(blank=True, db_index=True, help_text='Secondary identifier; always stored when available', max_length=13, null=True, unique=True),
        ),
    ]
